import { RedisCommandDoc } from './types';

export const BASIC_REDIS_COMMANDS: RedisCommandDoc[] = [
  // Strings
  {
    name: 'SET',
    syntax: 'SET key value [EX seconds|PX milliseconds|EXAT timestamp|PXAT milliseconds-timestamp|KEEPTTL] [NX|XX] [GET]',
    snippet: 'SET ${1:key} "${2:value}"',
    doc: 'Set the string value of a key with optional expiration TTL and condition (NX=if not exists, XX=if exists).',
    group: 'Strings',
  },
  {
    name: 'GET',
    syntax: 'GET key',
    snippet: 'GET ${1:key}',
    doc: 'Get the string value of a key. Returns `(nil)` if the key does not exist.',
    group: 'Strings',
  },
  {
    name: 'MGET',
    syntax: 'MGET key [key ...]',
    snippet: 'MGET ${1:key1} ${2:key2}',
    doc: 'Get the values of all specified keys.',
    group: 'Strings',
  },
  {
    name: 'MSET',
    syntax: 'MSET key value [key value ...]',
    snippet: 'MSET ${1:key1} "${2:val1}" ${3:key2} "${4:val2}"',
    doc: 'Set multiple keys to multiple values atomically.',
    group: 'Strings',
  },
  {
    name: 'INCR',
    syntax: 'INCR key',
    snippet: 'INCR ${1:key}',
    doc: 'Increments the number stored at key by one. Returns the value after increment.',
    group: 'Strings',
  },
  {
    name: 'INCRBY',
    syntax: 'INCRBY key increment',
    snippet: 'INCRBY ${1:key} ${2:10}',
    doc: 'Increments the number stored at key by the specified integer increment.',
    group: 'Strings',
  },
  {
    name: 'DECR',
    syntax: 'DECR key',
    snippet: 'DECR ${1:key}',
    doc: 'Decrements the number stored at key by one.',
    group: 'Strings',
  },
  {
    name: 'DECRBY',
    syntax: 'DECRBY key decrement',
    snippet: 'DECRBY ${1:key} ${2:10}',
    doc: 'Decrements the number stored at key by the specified integer decrement.',
    group: 'Strings',
  },
  {
    name: 'APPEND',
    syntax: 'APPEND key value',
    snippet: 'APPEND ${1:key} "${2:value}"',
    doc: 'Appends a string value to a key. Returns the length of the string after append.',
    group: 'Strings',
  },
  {
    name: 'STRLEN',
    syntax: 'STRLEN key',
    snippet: 'STRLEN ${1:key}',
    doc: 'Get the length of the value stored in a key.',
    group: 'Strings',
  },

  // Hashes
  {
    name: 'HSET',
    syntax: 'HSET key field value [field value ...]',
    snippet: 'HSET ${1:key} ${2:field} "${3:value}"',
    doc: 'Sets field in the hash stored at key to value.',
    group: 'Hashes',
  },
  {
    name: 'HGET',
    syntax: 'HGET key field',
    snippet: 'HGET ${1:key} ${2:field}',
    doc: 'Get the value of a hash field.',
    group: 'Hashes',
  },
  {
    name: 'HMSET',
    syntax: 'HMSET key field value [field value ...]',
    snippet: 'HMSET ${1:key} ${2:field1} "${3:val1}" ${4:field2} "${5:val2}"',
    doc: 'Sets the specified fields to their respective values in the hash stored at key.',
    group: 'Hashes',
  },
  {
    name: 'HMGET',
    syntax: 'HMGET key field [field ...]',
    snippet: 'HMGET ${1:key} ${2:field1} ${3:field2}',
    doc: 'Get the values of all the given hash fields.',
    group: 'Hashes',
  },
  {
    name: 'HGETALL',
    syntax: 'HGETALL key',
    snippet: 'HGETALL ${1:key}',
    doc: 'Get all the fields and values in a hash.',
    group: 'Hashes',
  },
  {
    name: 'HDEL',
    syntax: 'HDEL key field [field ...]',
    snippet: 'HDEL ${1:key} ${2:field}',
    doc: 'Deletes one or more hash fields.',
    group: 'Hashes',
  },
  {
    name: 'HEXISTS',
    syntax: 'HEXISTS key field',
    snippet: 'HEXISTS ${1:key} ${2:field}',
    doc: 'Determine if a hash field exists.',
    group: 'Hashes',
  },
  {
    name: 'HKEYS',
    syntax: 'HKEYS key',
    snippet: 'HKEYS ${1:key}',
    doc: 'Get all the fields in a hash.',
    group: 'Hashes',
  },
  {
    name: 'HVALS',
    syntax: 'HVALS key',
    snippet: 'HVALS ${1:key}',
    doc: 'Get all the values in a hash.',
    group: 'Hashes',
  },
  {
    name: 'HLEN',
    syntax: 'HLEN key',
    snippet: 'HLEN ${1:key}',
    doc: 'Get the number of fields in a hash.',
    group: 'Hashes',
  },
  {
    name: 'HINCRBY',
    syntax: 'HINCRBY key field increment',
    snippet: 'HINCRBY ${1:key} ${2:field} ${3:1}',
    doc: 'Increment the integer value of a hash field by the given number.',
    group: 'Hashes',
  },

  // Lists
  {
    name: 'LPUSH',
    syntax: 'LPUSH key element [element ...]',
    snippet: 'LPUSH ${1:key} "${2:element}"',
    doc: 'Prepend one or multiple elements to the head of a list.',
    group: 'Lists',
  },
  {
    name: 'RPUSH',
    syntax: 'RPUSH key element [element ...]',
    snippet: 'RPUSH ${1:key} "${2:element}"',
    doc: 'Append one or multiple elements to the tail of a list.',
    group: 'Lists',
  },
  {
    name: 'LPOP',
    syntax: 'LPOP key [count]',
    snippet: 'LPOP ${1:key}',
    doc: 'Removes and returns the first elements of the list stored at key.',
    group: 'Lists',
  },
  {
    name: 'RPOP',
    syntax: 'RPOP key [count]',
    snippet: 'RPOP ${1:key}',
    doc: 'Removes and returns the last elements of the list stored at key.',
    group: 'Lists',
  },
  {
    name: 'LRANGE',
    syntax: 'LRANGE key start stop',
    snippet: 'LRANGE ${1:key} ${2:0} ${3:-1}',
    doc: 'Get a range of elements from a list (0 is first, -1 is last).',
    group: 'Lists',
  },
  {
    name: 'LLEN',
    syntax: 'LLEN key',
    snippet: 'LLEN ${1:key}',
    doc: 'Get the length of a list.',
    group: 'Lists',
  },
  {
    name: 'LINDEX',
    syntax: 'LINDEX key index',
    snippet: 'LINDEX ${1:key} ${2:0}',
    doc: 'Get an element from a list by its index.',
    group: 'Lists',
  },
  {
    name: 'LSET',
    syntax: 'LSET key index element',
    snippet: 'LSET ${1:key} ${2:0} "${3:element}"',
    doc: 'Set the value of an element in a list by its index.',
    group: 'Lists',
  },
  {
    name: 'LREM',
    syntax: 'LREM key count element',
    snippet: 'LREM ${1:key} ${2:1} "${3:element}"',
    doc: 'Remove elements from a list matching the specified element.',
    group: 'Lists',
  },
];
