// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddColumn(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddColumn'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function CheckDockerAvailability() {
  return window['go']['main']['App']['CheckDockerAvailability']();
}

export function ClearQueryLogs() {
  return window['go']['main']['App']['ClearQueryLogs']();
}

export function CloseContainerExec(arg1) {
  return window['go']['main']['App']['CloseContainerExec'](arg1);
}

export function CloseProjectConnections() {
  return window['go']['main']['App']['CloseProjectConnections']();
}

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function CommitChanges(arg1, arg2) {
  return window['go']['main']['App']['CommitChanges'](arg1, arg2);
}

export function ConnectRedis(arg1) {
  return window['go']['main']['App']['ConnectRedis'](arg1);
}

export function CreateProjectFileDialog(arg1) {
  return window['go']['main']['App']['CreateProjectFileDialog'](arg1);
}

export function CreateRedisKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateRedisKey'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTerminalSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTerminalSession'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteRedisKey(arg1, arg2) {
  return window['go']['main']['App']['DeleteRedisKey'](arg1, arg2);
}

export function DeleteRedisKeysBatch(arg1, arg2) {
  return window['go']['main']['App']['DeleteRedisKeysBatch'](arg1, arg2);
}

export function DeleteTableRows(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteTableRows'](arg1, arg2, arg3, arg4, arg5);
}

export function DropColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DropColumn'](arg1, arg2, arg3, arg4);
}

export function ExecuteHttpRequest(arg1) {
  return window['go']['main']['App']['ExecuteHttpRequest'](arg1);
}

export function ExecuteRawQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteRawQuery'](arg1, arg2, arg3);
}

export function ExecuteRedisCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRedisCommand'](arg1, arg2);
}

export function ExplainQuery(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExplainQuery'](arg1, arg2, arg3, arg4);
}

export function ExportDatabaseSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDatabaseSQL'](arg1, arg2, arg3);
}

export function ExportTableSQL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportTableSQL'](arg1, arg2, arg3, arg4);
}

export function FetchChanges(arg1) {
  return window['go']['main']['App']['FetchChanges'](arg1);
}

export function FlushRedisDB(arg1) {
  return window['go']['main']['App']['FlushRedisDB'](arg1);
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetDatabaseSchemaDetails(arg1, arg2) {
  return window['go']['main']['App']['GetDatabaseSchemaDetails'](arg1, arg2);
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetEnumValues(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEnumValues'](arg1, arg2, arg3);
}

export function GetFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2, arg3);
}

export function GetQueryLogs() {
  return window['go']['main']['App']['GetQueryLogs']();
}

export function GetRedisKeyDetails(arg1, arg2) {
  return window['go']['main']['App']['GetRedisKeyDetails'](arg1, arg2);
}

export function GetRepoStatus(arg1) {
  return window['go']['main']['App']['GetRepoStatus'](arg1);
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetTableData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4);
}

export function GetTableSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function ImportSQLScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportSQLScript'](arg1, arg2, arg3);
}

export function InitRepository(arg1) {
  return window['go']['main']['App']['InitRepository'](arg1);
}

export function InitializeRepositoryWithOptions(arg1) {
  return window['go']['main']['App']['InitializeRepositoryWithOptions'](arg1);
}

export function IsGitRepository(arg1) {
  return window['go']['main']['App']['IsGitRepository'](arg1);
}

export function ListContainers(arg1) {
  return window['go']['main']['App']['ListContainers'](arg1);
}

export function LoadEnvironmentsData() {
  return window['go']['main']['App']['LoadEnvironmentsData']();
}

export function LoadHttpClientData() {
  return window['go']['main']['App']['LoadHttpClientData']();
}

export function LoadRedisConnections() {
  return window['go']['main']['App']['LoadRedisConnections']();
}

export function LoadSqlQueriesData() {
  return window['go']['main']['App']['LoadSqlQueriesData']();
}

export function OpenProjectFileDialog() {
  return window['go']['main']['App']['OpenProjectFileDialog']();
}

export function OpenRepositoryDialog() {
  return window['go']['main']['App']['OpenRepositoryDialog']();
}

export function PullChanges(arg1) {
  return window['go']['main']['App']['PullChanges'](arg1);
}

export function PushChanges(arg1) {
  return window['go']['main']['App']['PushChanges'](arg1);
}

export function ReadProjectFile(arg1) {
  return window['go']['main']['App']['ReadProjectFile'](arg1);
}

export function RemoveContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2);
}

export function RenameColumn(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RenameColumn'](arg1, arg2, arg3, arg4, arg5);
}

export function ResizeContainerExec(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeContainerExec'](arg1, arg2, arg3);
}

export function ResizeTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminalSession'](arg1, arg2, arg3);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveEnvironmentsData(arg1) {
  return window['go']['main']['App']['SaveEnvironmentsData'](arg1);
}

export function SaveHttpClientData(arg1) {
  return window['go']['main']['App']['SaveHttpClientData'](arg1);
}

export function SaveProjectFile(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectFile'](arg1, arg2);
}

export function SaveRedisConnections(arg1) {
  return window['go']['main']['App']['SaveRedisConnections'](arg1);
}

export function SaveSQLDumpDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveSQLDumpDialog'](arg1, arg2);
}

export function SaveSqlQueriesData(arg1) {
  return window['go']['main']['App']['SaveSqlQueriesData'](arg1);
}

export function ScanRedisKeys(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScanRedisKeys'](arg1, arg2, arg3, arg4);
}

export function SelectFilesDialog() {
  return window['go']['main']['App']['SelectFilesDialog']();
}

export function SetRedisTTL(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRedisTTL'](arg1, arg2, arg3);
}

export function StageAll(arg1) {
  return window['go']['main']['App']['StageAll'](arg1);
}

export function StageFile(arg1, arg2) {
  return window['go']['main']['App']['StageFile'](arg1, arg2);
}

export function StartAutoWatch(arg1) {
  return window['go']['main']['App']['StartAutoWatch'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartContainerExec(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartContainerExec'](arg1, arg2, arg3, arg4);
}

export function StartLogStream(arg1) {
  return window['go']['main']['App']['StartLogStream'](arg1);
}

export function StartTerminalSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartTerminalSession'](arg1, arg2, arg3, arg4, arg5);
}

export function StopAutoWatch() {
  return window['go']['main']['App']['StopAutoWatch']();
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopLogStream(arg1) {
  return window['go']['main']['App']['StopLogStream'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TruncateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['TruncateTable'](arg1, arg2, arg3);
}

export function UnstageAll(arg1) {
  return window['go']['main']['App']['UnstageAll'](arg1);
}

export function UnstageFile(arg1, arg2) {
  return window['go']['main']['App']['UnstageFile'](arg1, arg2);
}

export function UpdateRedisKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateRedisKey'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTableRows(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTableRows'](arg1, arg2, arg3, arg4, arg5);
}

export function WipeLegacyStorage() {
  return window['go']['main']['App']['WipeLegacyStorage']();
}

export function WriteContainerExec(arg1, arg2) {
  return window['go']['main']['App']['WriteContainerExec'](arg1, arg2);
}

export function WriteTerminalSession(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminalSession'](arg1, arg2);
}
