// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddColumn(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<boolean>;

export function ClearQueryLogs():Promise<boolean>;

export function DeleteConnection(arg1:string):Promise<boolean>;

export function DropColumn(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function GetDatabases(arg1:main.ConnectionConfig):Promise<Array<string>>;

export function GetQueryLogs():Promise<Array<main.QueryLog>>;

export function GetSavedConnections():Promise<Array<main.ConnectionConfig>>;

export function GetTableData(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.TableDataResult>;

export function GetTableSchema(arg1:main.ConnectionConfig,arg2:string,arg3:string):Promise<Array<main.TableColumn>>;

export function GetTables(arg1:main.ConnectionConfig,arg2:string):Promise<Array<string>>;

export function RenameColumn(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function SaveConnection(arg1:main.ConnectionConfig):Promise<boolean|string>;

export function TestConnection(arg1:main.ConnectionConfig):Promise<boolean|string>;
