// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddColumn(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddColumn'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ClearQueryLogs() {
  return window['go']['main']['App']['ClearQueryLogs']();
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteTableRows(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteTableRows'](arg1, arg2, arg3, arg4, arg5);
}

export function DropColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DropColumn'](arg1, arg2, arg3, arg4);
}

export function ExecuteRawQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteRawQuery'](arg1, arg2, arg3);
}

export function ExportDatabaseSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDatabaseSQL'](arg1, arg2, arg3);
}

export function ExportTableSQL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportTableSQL'](arg1, arg2, arg3, arg4);
}

export function GetDatabaseSchemaDetails(arg1, arg2) {
  return window['go']['main']['App']['GetDatabaseSchemaDetails'](arg1, arg2);
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetEnumValues(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEnumValues'](arg1, arg2, arg3);
}

export function GetQueryLogs() {
  return window['go']['main']['App']['GetQueryLogs']();
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetTableData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4);
}

export function GetTableSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function ImportSQLScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportSQLScript'](arg1, arg2, arg3);
}

export function RenameColumn(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RenameColumn'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveSQLDumpDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveSQLDumpDialog'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TruncateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['TruncateTable'](arg1, arg2, arg3);
}

export function UpdateTableRows(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTableRows'](arg1, arg2, arg3, arg4, arg5);
}
