// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddColumn(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<boolean>;

export function CheckConnection():Promise<boolean|string>;

export function CheckDockerAvailability():Promise<boolean|string>;

export function ClearQueryLogs():Promise<boolean>;

export function CloseContainerExec(arg1:string):Promise<void>;

export function CloseProjectConnections():Promise<boolean>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function ConnectRedis(arg1:main.RedisConnectionConfig):Promise<main.RedisConnectResult>;

export function CreateProjectFileDialog(arg1:string):Promise<main.ProjectFileResult>;

export function CreateRedisKey(arg1:main.RedisConnectionConfig,arg2:string,arg3:string,arg4:any,arg5:number):Promise<boolean>;

export function DeleteConnection(arg1:string):Promise<boolean>;

export function DeleteRedisKey(arg1:main.RedisConnectionConfig,arg2:string):Promise<boolean>;

export function DeleteRedisKeysBatch(arg1:main.RedisConnectionConfig,arg2:Array<string>):Promise<number>;

export function DeleteTableRows(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<boolean>;

export function DropColumn(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function ExecuteHttpRequest(arg1:main.HttpRequestPayload):Promise<main.HttpResponsePayload>;

export function ExecuteRawQuery(arg1:main.ConnectionConfig,arg2:string,arg3:string):Promise<Array<main.QueryResult>>;

export function ExecuteRedisCommand(arg1:main.RedisConnectionConfig,arg2:string):Promise<main.RedisCommandResult>;

export function ExplainQuery(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:boolean):Promise<main.ExplainPlanResult>;

export function ExportDatabaseSQL(arg1:main.ConnectionConfig,arg2:string,arg3:boolean):Promise<string>;

export function ExportTableSQL(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function FlushRedisDB(arg1:main.RedisConnectionConfig):Promise<boolean>;

export function GetDatabaseSchemaDetails(arg1:main.ConnectionConfig,arg2:string):Promise<main.DatabaseSchema>;

export function GetDatabases(arg1:main.ConnectionConfig):Promise<Array<string>>;

export function GetEnumValues(arg1:main.ConnectionConfig,arg2:string,arg3:string):Promise<Array<string>>;

export function GetQueryLogs():Promise<Array<main.QueryLog>>;

export function GetRedisKeyDetails(arg1:main.RedisConnectionConfig,arg2:string):Promise<main.RedisKeyDetail>;

export function GetSavedConnections():Promise<Array<main.ConnectionConfig>>;

export function GetTableData(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:main.DataQueryOptions):Promise<main.TableDataResult>;

export function GetTableSchema(arg1:main.ConnectionConfig,arg2:string,arg3:string):Promise<Array<main.TableColumn>>;

export function GetTables(arg1:main.ConnectionConfig,arg2:string):Promise<Array<string>>;

export function ImportSQLScript(arg1:main.ConnectionConfig,arg2:string,arg3:string):Promise<main.ImportResult>;

export function ListContainers(arg1:boolean):Promise<Array<main.DockerProjectGroup>>;

export function LoadEnvironmentsData():Promise<string>;

export function LoadHttpClientData():Promise<string>;

export function LoadRedisConnections():Promise<string>;

export function LoadSqlQueriesData():Promise<string>;

export function OpenProjectFileDialog():Promise<main.ProjectFileResult>;

export function ReadProjectFile(arg1:string):Promise<main.ProjectFileResult>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<boolean>;

export function RenameColumn(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function ResizeContainerExec(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartContainer(arg1:string):Promise<boolean>;

export function SaveConnection(arg1:main.ConnectionConfig):Promise<boolean|string>;

export function SaveEnvironmentsData(arg1:string):Promise<void>;

export function SaveHttpClientData(arg1:string):Promise<void>;

export function SaveProjectFile(arg1:string,arg2:string):Promise<boolean>;

export function SaveRedisConnections(arg1:string):Promise<void>;

export function SaveSQLDumpDialog(arg1:string,arg2:string):Promise<string>;

export function SaveSqlQueriesData(arg1:string):Promise<void>;

export function ScanRedisKeys(arg1:main.RedisConnectionConfig,arg2:string,arg3:number,arg4:number):Promise<main.RedisScanResult>;

export function SelectFilesDialog():Promise<Array<main.SelectedFileMeta>>;

export function SetRedisTTL(arg1:main.RedisConnectionConfig,arg2:string,arg3:number):Promise<boolean>;

export function StartContainer(arg1:string):Promise<boolean>;

export function StartContainerExec(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function StartLogStream(arg1:string):Promise<void>;

export function StartTerminalSession(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function StopContainer(arg1:string):Promise<boolean>;

export function StopLogStream(arg1:string):Promise<void>;

export function TestConnection(arg1:main.ConnectionConfig):Promise<boolean|string>;

export function TruncateTable(arg1:main.ConnectionConfig,arg2:string,arg3:string):Promise<boolean>;

export function UpdateRedisKey(arg1:main.RedisConnectionConfig,arg2:string,arg3:string,arg4:any,arg5:number):Promise<boolean>;

export function UpdateTableRows(arg1:main.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:Array<main.RowUpdate>):Promise<boolean>;

export function WipeLegacyStorage():Promise<boolean>;

export function WriteContainerExec(arg1:string,arg2:string):Promise<void>;

export function WriteTerminalSession(arg1:string,arg2:string):Promise<void>;
